### ISSUE TITLE
EuclidDataFile2.0train.csv

### ISSUE THREAD

**Issue by parlange** [JoshWilde/LensFindery-McLensFinderFace#1]
Hi @JoshWilde 

I am trying to run the CNN_training notebook.

Where can I find EuclidDataFile2.0train.csv?

Thank you

**Comment by JoshWilde** [comment]
Hi,
You should be able to find EuclidDataFile2.0train.csv here http://metcalf1.difa.unibo.it/blf-portal/gg_challenge.html
It is under Log of Lens properties for Challenge 2.0

**Comment by parlange** [comment]
Thank you @JoshWilde 

On CNN TRAINING, the first cell has a problem with Load_Images.py

```
from Load_Images import J_LoadImages, Y_LoadImages, H_LoadImages, JYH_LoadImages, VIS_LoadImages, OU66_LoadImages, OU200_LoadImages

from CNN_Networks import J_CNN, Y_CNN, H_CNN, JYH_CNN, VIS_CNN, OU66_CNN, OU200_CNN
```

```
`Traceback (most recent call last):
  File "/home/parlange/anaconda3/envs/torch/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_8888/4046551506.py", line 15, in <module>
    from Load_Images import J_LoadImages, Y_LoadImages, H_LoadImages, JYH_LoadImages, VIS_LoadImages, OU66_LoadImages, OU200_LoadImages
  File "/home/parlange/LensFindery-McLensFinderFace/CNN Models/Load_Images.py", line 51, in <module>
    Images, NewOutput = LoadImages(Output)
                        ^^^^^^^^^^
NameError: name 'LoadImages' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/parlange/anaconda3/envs/torch/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 2144, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/parlange/anaconda3/envs/torch/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1435, in structured_traceback
    return FormattedTB.structured_traceback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/parlange/anaconda3/envs/torch/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1326, in structured_traceback
    return VerboseTB.structured_traceback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/parlange/anaconda3/envs/torch/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1173, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/parlange/anaconda3/envs/torch/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1088, in format_exception_as_a_whole
    frames.append(self.format_record(record))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/parlange/anaconda3/envs/torch/lib/python3.11/site-packages/IPython/core/ultratb.py", line 970, in format_record
    frame_info.lines, Colors, self.has_colors, lvals
    ^^^^^^^^^^^^^^^^
  File "/home/parlange/anaconda3/envs/torch/lib/python3.11/site-packages/IPython/core/ultratb.py", line 792, in lines
    return self._sd.lines
           ^^^^^^^^^^^^^^
  File "/home/parlange/anaconda3/envs/torch/lib/python3.11/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
                                               ^^^^^^^^^^^^^^
  File "/home/parlange/anaconda3/envs/torch/lib/python3.11/site-packages/stack_data/core.py", line 698, in lines
    pieces = self.included_pieces
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/parlange/anaconda3/envs/torch/lib/python3.11/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
                                               ^^^^^^^^^^^^^^
  File "/home/parlange/anaconda3/envs/torch/lib/python3.11/site-packages/stack_data/core.py", line 649, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
                             ^^^^^^^^^^^^^^^^^^^^
  File "/home/parlange/anaconda3/envs/torch/lib/python3.11/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
                                               ^^^^^^^^^^^^^^
  File "/home/parlange/anaconda3/envs/torch/lib/python3.11/site-packages/stack_data/core.py", line 628, in executing_piece
    return only(
           ^^^^^
  File "/home/parlange/anaconda3/envs/torch/lib/python3.11/site-packages/executing/executing.py", line 164, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0` 
```

If the funtion is called as J_LoadImages then the next message is that Output is not defined.

**Comment by JoshWilde** [comment]
Hi,
Thank you for pointing out these errors. 
I've removed `Images, NewOutput = LoadImages(Output)` from `Load_Images` this was a typo and must have been introduced when I was trying to tidy up this code. I have also added `Output = LoadData(Number)` to the notebook. 
The training data should be on the same website as EuclidDataFile2.0train.csv. There is some cleaning that needs to be done to EuclidDataFile2.0train.csv.
Hopefully this should all work now,
Thank You
